### PR TITLE
moving to new transition group method

### PR DESCRIPTION
**Pull request by andrewmartin**
just thought I'd offer this little PR to get people off of the annoying depreciation warnings...

### CODE REVIEW

**Comment by kylecesmat** [comment]
Looks great! Thanks for the contribution!

**Comment by andrewmartin** [comment]
You got it! Love this package btw. 🥇

**Comment by kylecesmat** [comment]
@andrewmartin this has been released in `3.2.0`

**Comment by andrewmartin** [comment]
🙌

**Pull request merged**
